keys:
  - &username age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
creation_rules:
  - path_regex: ^(/dev/stdin|\.canivete/(sops/default\.yaml|opentofu/[^/]+/terraform\.tfstate.*))$
    key_groups:
      - age:
          - *username
