opentofu_pw: ENC[AES256_GCM,data:3oapLdwFp4g=,iv:5AbZhWFqdMJ5WTnyrV+gHk3vB6yg4uNh+f0o/TtvEMM=,tag:ohh9K4FQc8h07bFaQoZUug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMmR5TU5LNXJDVlRVQ0t3
            Q2tHcXNkVmhZelp4dlRyM0ZNOWx0MzJabUd3Ck11SGN3M1BjaU5wOEVzbm5YQUpS
            Q0JadjNsQzBDZVZ4djZNWjdWQzFPVTAKLS0tIHlDZU9hRWxXNEtuQ2F3VEJVWUtl
            YVZLTzNSZ3hsSUN1YVJHSnFtd2llbGsKqeUxhg7J9JRszahCN1ZfF0PojMygWc6A
            Ree9aKliNuOAK+K0pyQvJVabHdwUeB8SdOGvnPaJckSYSvbkw/NBSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T21:36:28Z"
    mac: ENC[AES256_GCM,data:msCqGeHXezcvkEocQRB2rskgzBjY2jVuKIV0vmuowiEGWUqv4fcRCGHom21kQsWEB86uQrhAKJQ/qt5avSC4/u+J3AhcenKLX5tKrbzQxvSVOPr6HnL/s/nsQ2/J1wNtPIXQ7SK350leAsNLQBDL0JS1UbEujWEWQEx5iUE576M=,iv:qs3rQBsvX0O2zxpqHNdQ27hBKw62w3Xo4cfSJPnt3ZA=,tag:BFXEwEk97u2qkNviRm20nA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
